
import { Language, Major, InternshipSite, DocumentForm, FormCategory, ScheduleEvent, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.TH]: {
    title: "หน่วยจัดการศึกษาวิทยาศาสตร์บูรณาการกับการทำงาน (วบง.)",
    subtitle: "คณะวิทยาศาสตร์และเทคโนโลยี มหาวิทยาลัยฟาฏอนี",
    landingHeading: "การฝึกประสบการณ์และสหกิจศึกษา",
    loginStudent: "ทางเข้าสำหรับนักศึกษา",
    loginAdmin: "ระบบจัดการสำหรับผู้ดูแล",
    studentIdPlaceholder: "รหัสประจำตัวนักศึกษา",
    adminPasswordPlaceholder: "รหัสผ่านเจ้าหน้าที่",
    loginButton: "ยืนยันการเข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    internshipSites: "ฐานข้อมูลสถานประกอบการ",
    forms: "ศูนย์บริการเอกสารอิเล็กทรอนิกส์",
    halalMajor: "วิชาเอกอุตสาหกรรมฮาลาล",
    digitalMajor: "วิชาเอกเทคโนโลยีดิจิทัล",
    activeSites: "กำลังเปิดรับสมัคร",
    pastSites: "ประวัติการฝึกงาน",
    download: "ดาวน์โหลดเอกสาร",
    adminPanel: "แผงควบคุมระบบจัดการ",
    addSite: "เพิ่มข้อมูลหน่วยงาน",
    edit: "แก้ไข",
    delete: "ลบ",
    save: "บันทึกข้อมูล",
    cancel: "ยกเลิก",
    name: "ชื่อหน่วยงาน",
    location: "สถานที่ตั้ง",
    description: "รายละเอียด",
    status: "สถานะ",
    major: "สาขาวิชา",
    urlLabel: "เว็บไซต์องค์กร",
    selectMajorTitle: "เลือกหลักสูตรการศึกษา",
    selectMajorSubtitle: "เพื่อเข้าถึงข้อมูลที่ตรงตามวิชาเอกของท่าน",
    startNow: "เข้าสู่เว็บไซต์",
    selectLanguagePrompt: "กรุณาเลือกภาษา",
    schedule: "ขั้นตอนการดำเนินงานและกำหนดการ",
    appForms: "1. เอกสารประกอบการสมัคร",
    monitoringForms: "2. เอกสารระหว่างการฝึกปฏิบัติงาน",
    email: "อีเมลติดต่อ",
    phone: "หมายเลขโทรศัพท์",
    visitWebsite: "ดูรายละเอียด"
  },
  [Language.EN]: {
    title: "Work-Integrated Science Education Unit (WISE)",
    subtitle: "Faculty of Science and Technology, Fatoni University",
    landingHeading: "Internship & Cooperative Education",
    loginStudent: "Student Access",
    loginAdmin: "Administrative Dashboard",
    studentIdPlaceholder: "Student Identification Number",
    adminPasswordPlaceholder: "Authorized Password",
    loginButton: "Authenticate",
    logout: "Sign Out",
    internshipSites: "Placement Database",
    forms: "Document Resource Center",
    halalMajor: "Halal Science & Industry",
    digitalMajor: "Digital Technology",
    activeSites: "Active Vacancies",
    pastSites: "Placement Records",
    download: "Download",
    adminPanel: "Admin Terminal",
    addSite: "Add Placement Site",
    edit: "Modify",
    delete: "Remove",
    save: "Save Changes",
    cancel: "Cancel",
    name: "Organization Name",
    location: "Location",
    description: "Scope of Work",
    status: "Status",
    major: "Academic Major",
    urlLabel: "Official Website",
    selectMajorTitle: "Academic Major Selection",
    selectMajorSubtitle: "Accessing information specific to your curriculum",
    startNow: "Enter System",
    selectLanguagePrompt: "Select Language",
    schedule: "Procedural Roadmap & Timeline",
    appForms: "1. Application Phase Documents",
    monitoringForms: "2. Internship Phase Documents",
    email: "Official Email",
    phone: "Contact Number",
    visitWebsite: "Full Details"
  },
  [Language.AR]: {
    title: "وحدة تعليم العلوم المتكاملة مع العمل (WISE)",
    subtitle: "كلية العلوم والتكنولوجيا، جامعة فطاني",
    landingHeading: "التدريب التعاوني والتعليم المهني",
    loginStudent: "دخول الطلاب",
    loginAdmin: "نظام الإدارة الأكاديمية",
    studentIdPlaceholder: "الرقم الجامعي",
    adminPasswordPlaceholder: "كلمة المرور الإدارية",
    loginButton: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    internshipSites: "قاعدة بيانات جهات التدريب",
    forms: "مركز النماذج والوثائق",
    halalMajor: "علوم وصناعة الحلال",
    digitalMajor: "التكنولوجيا الرقمية",
    activeSites: "الفرص المتاحة حالياً",
    pastSites: "سجلات التدريب السابقة",
    download: "تحميل",
    adminPanel: "لوحة التحكم الإدارية",
    addSite: "إضافة جهة تدريب",
    edit: "تعديل",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    name: "اسم المؤسسة",
    location: "الموقع",
    description: "تفاصيل التدريب",
    status: "الحالة",
    major: "التخصص الأكاديمي",
    urlLabel: "الموقع الإلكتروني",
    selectMajorTitle: "يرجى اختيار التخصص",
    selectMajorSubtitle: "للوصول إلى المعلومات المتعلقة بمسارك الدراسي",
    startNow: "دخول النظام",
    selectLanguagePrompt: "اختر لغة النظام",
    schedule: "الإجراءات والجدول الزمني",
    appForms: "١. مستندات مرحلة التقديم",
    monitoringForms: "٢. مستندات مرحلة التدريب",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    visitWebsite: "عرض التفاصيل"
  },
  [Language.ID]: {
    title: "Unit Pengelola Pendidikan Sains Terintegrasi Kerja (WISE)",
    subtitle: "Fakultas Sains dan Teknologi, Universitas Fatoni",
    landingHeading: "Magang & Pendidikan Kooperatif",
    loginStudent: "Akses Mahasiswa",
    loginAdmin: "Terminal Administrasi",
    studentIdPlaceholder: "Nomor Induk Mahasiswa (NIM)",
    adminPasswordPlaceholder: "Kata Sandi Administrator",
    loginButton: "Autentikasi",
    logout: "Keluar",
    internshipSites: "Database Penempatan Magang",
    forms: "Pusat Dokumen Digital",
    halalMajor: "Sains & Industri Halal",
    digitalMajor: "Teknologi Digital",
    activeSites: "Pendaftaran Aktif",
    pastSites: "Riwayat Penempatan",
    download: "Unduh",
    adminPanel: "Dasbor Admin",
    addSite: "Tambah Entitas Penempatan",
    edit: "Sunting",
    delete: "Hapus",
    save: "Simpan",
    cancel: "Batal",
    name: "Nama Lembaga",
    location: "Lokasi",
    description: "Deskripsi Kerja",
    status: "Status",
    major: "Program Studi",
    urlLabel: "Situs Web Resmi",
    selectMajorTitle: "Pilihan Program Studi",
    selectMajorSubtitle: "Akses informasi berdasarkan kurikulum Anda",
    startNow: "Masuk Sistem",
    selectLanguagePrompt: "Pilih Bahasa",
    schedule: "Prosedur dan Jadwal Pelaksanaan",
    appForms: "1. Dokumen Tahap Pendaftaran",
    monitoringForms: "2. Dokumen Tahap Pelaksanaan",
    email: "Email Kontak",
    phone: "Nomor Telepon",
    visitWebsite: "Detail Lengkap"
  },
  [Language.MS]: {
    title: "Unit Pengurusan Pendidikan Sains Bersepadu Kerja (WISE)",
    subtitle: "Fakulti Sains dan Teknologi, Universiti Fatoni",
    landingHeading: "Latihan Industri & Kooperatif",
    loginStudent: "Akses Pelajar",
    loginAdmin: "Terminal Pentadbiran",
    studentIdPlaceholder: "Nombor Matrik Pelajar",
    adminPasswordPlaceholder: "Kata Laluan Pentadbir",
    loginButton: "Log Masuk",
    logout: "Log Keluar",
    internshipSites: "Pangkalan Data Latihan Industri",
    forms: "Pusat Sumber Dokumen",
    halalMajor: "Sains & Industri Halal",
    digitalMajor: "Teknologi Digital",
    activeSites: "Pengambilan Terbuka",
    pastSites: "Rekod Penempatan",
    download: "Muat Turun",
    adminPanel: "Papan Pemuka Pentadbiran",
    addSite: "Tambah Tapak Penempatan",
    edit: "Kemaskini",
    delete: "Padam",
    save: "Simpan",
    cancel: "Batal",
    name: "Nama Organisasi",
    location: "Lokasi",
    description: "Skop Kerja",
    status: "Status",
    major: "Program Akademik",
    urlLabel: "Laman Web Rasmi",
    selectMajorTitle: "Pilihan Program Akademik",
    selectMajorSubtitle: "Maklumat mengikut aliran pengajian anda",
    startNow: "Masuk Sistem",
    selectLanguagePrompt: "Pilih Bahasa",
    schedule: "Prosedur dan Jadual Pelaksanaan",
    appForms: "1. Dokumen Fasa Permohonan",
    monitoringForms: "2. Dokumen Fasa Latihan",
    email: "E-mel Rasmi",
    phone: "Talian Perhubungan",
    visitWebsite: "Maklumat Lanjut"
  }
};

export const INITIAL_SITES: InternshipSite[] = [
  {
    id: '1',
    name: {
      th: 'บริษัท ซีพี ออลล์ จำกัด (มหาชน)',
      en: 'CP ALL Public Company Limited',
      ar: 'شركة سي بي أول المحدودة العامة',
      id: 'CP ALL Perusahaan Terbuka',
      ms: 'CP ALL Syarikat Awam Berhad'
    },
    location: {
      th: 'กรุงเทพมหานคร, ประเทศไทย',
      en: 'Bangkok, Thailand',
      ar: 'بانكوك، تايلاند',
      id: 'Bangkok, Thailand',
      ms: 'Bangkok, Thailand'
    },
    description: {
      th: 'ศึกษาและฝึกงานด้านมาตรฐานความปลอดภัยอาหารฮาลาลและระบบโลจิสติกส์ในร้านสะดวกซื้อระดับประเทศ',
      en: 'Professional training in Halal food safety standards and nationwide retail logistics operations.',
      ar: 'تدريب مهني في معايير سلامة الأغذية الحلال وعمليات الخدمات اللوجستية للبيع بالتجزئة على مستوى البلاد.',
      id: 'Pelatihan profesional dalam standar keamanan pangan Halal dan operasi logistik ritel nasional.',
      ms: 'Latihan profesional dalam piawaian keselamatan makanan Halal dan operasi logistik runcit di seluruh negara.'
    },
    status: 'active',
    major: Major.HALAL_FOOD,
    contactLink: 'https://www.cpall.co.th/',
    email: 'contact@cpall.co.th',
    phone: '02-071-9000'
  },
  {
    id: '2',
    name: {
      th: 'ศูนย์วิทยาศาสตร์ฮาลาล จุฬาลงกรณ์มหาวิทยาลัย',
      en: 'The Halal Science Center, Chulalongkorn University',
      ar: 'مركز علوم الحلال بجامعة شولالونغكورน',
      id: 'Pusat Sains Halal, Universitas Chulalongkorn',
      ms: 'Pusat Sains Halal, Universiti Chulalongkorn'
    },
    location: {
      th: 'กรุงเทพมหานคร, ประเทศไทย',
      en: 'Bangkok, Thailand',
      ar: 'بانكوك، تايلاند',
      id: 'Bangkok, Thailand',
      ms: 'Bangkok, Thailand'
    },
    description: {
      th: 'วิจัยและทดสอบทางวิทยาศาสตร์ฮาลาลในห้องปฏิบัติการที่ทันสมัย เพื่อการคุ้มครองผู้บริโภคในระดับสากล',
      en: 'Advanced Halal science research and laboratory testing for global consumer protection standards.',
      ar: 'أبحاث متقدمة في علوم الحلال واختبارات معملية لمعايير حماية المستهلك العالمية.',
      id: 'Penelitian sains Halal tingkat lanjut dan pengujian laboratorium untuk standar perlindungan konsumen global.',
      ms: 'Penyelidikan sains Halal termaju และ ujian makmal untuk piawaian perlindungan pengguna global.'
    },
    status: 'archived',
    major: Major.HALAL_FOOD,
    email: 'hsc@chula.ac.th'
  },
  {
    id: '3',
    name: {
      th: 'บริษัท การีนา ออนไลน์ (ประเทศไทย) จำกัด',
      en: 'Garena Online (Thailand) Co., Ltd.',
      ar: 'شركة غارينا أونلاين (تايلاند) المحدودة',
      id: 'Garena Online (Thailand) Co., Ltd.',
      ms: 'Garena Online (Thailand) Co., Ltd.'
    },
    location: {
      th: 'กรุงเทพมหานคร, ประเทศไทย',
      en: 'Bangkok, Thailand',
      ar: 'بانكوك، تايلاند',
      id: 'Bangkok, Thailand',
      ms: 'Bangkok, Thailand'
    },
    description: {
      th: 'พัฒนาซอฟต์แวร์ เกม และแพลตฟอร์มอีสปอร์ตระดับสากล สำหรับนักศึกษาเทคโนโลยีดิจิทัล',
      en: 'Software engineering, game development, and international e-sports platform operations for digital students.',
      ar: 'هندسة البرمجيات وتطوير الألعاب وعمليات منصات الرياضات الإلكترونية الدولية لطلاب التكنولوجيا الرقمية.',
      id: 'Teknik perangkat lunak, pengembangan game, dan operasi platform e-sports internasional untuk mahasiswa teknologi digital.',
      ms: 'Kejuruteraan perisian, pembangunan permainan, dan operasi platform e-sukan antarabangsa untuk pelajar teknologi digital.'
    },
    status: 'active',
    major: Major.DIGITAL_TECH,
    phone: '02-118-9191',
    contactLink: 'https://www.garena.co.th/'
  }
];

export const INITIAL_SCHEDULE: ScheduleEvent[] = [
  { 
    id: 's1', 
    event: {
      th: 'ปฐมนิเทศนักศึกษาก่อนฝึกงาน',
      en: 'Pre-Internship Orientation Session',
      ar: 'جلسة توجيه الطلاب قبل التدريب',
      id: 'Sesi Orientasi Pra-Magang',
      ms: 'Sesi Orientasi Pra-Latihan Industri'
    }, 
    date: {
      th: 'มิถุนายน 2567',
      en: 'June 2024',
      ar: 'يونيو ٢٠٢٤',
      id: 'Juni 2024',
      ms: 'Jun 2024'
    }, 
    status: 'upcoming' 
  },
  { 
    id: 's2', 
    event: {
      th: 'ยื่นเอกสารสมัครสถานประกอบการ',
      en: 'Placement Application Submission',
      ar: 'تقديم طلبات الالتحاق بجهات التدريب',
      id: 'Pengajuan Berkas Pendaftaran Tempat PKL',
      ms: 'Penyerahan Dokumen Permohonan Penempatan'
    }, 
    date: {
      th: 'กรกฎาคม 2567',
      en: 'July 2024',
      ar: 'ยوليو ٢٠٢٤',
      id: 'Juli 2024',
      ms: 'Jul 2024'
    }, 
    status: 'upcoming' 
  },
  { 
    id: 's3', 
    event: {
      th: 'เริ่มการฝึกประสบการณ์',
      en: 'Commencement of Practical Training',
      ar: 'بدء التدريب มيداني الفعلي',
      id: 'Awal Pelaksanaan Praktik Kerja Lapangan',
      ms: 'Permulaan Latihan Industri Secara Rasmi'
    }, 
    date: {
      th: 'สิงหาคม 2567',
      en: 'August 2024',
      ar: 'أغسطس ٢٠٢٤',
      id: 'Agustus 2024',
      ms: 'Ogos 2024'
    }, 
    status: 'upcoming' 
  },
];

export const INITIAL_FORMS: DocumentForm[] = [
  { id: 'f1', title: 'แบบขออนุมัติฝึกงาน (วบง.01)', category: FormCategory.APPLICATION, url: '#' },
  { id: 'f2', title: 'หนังสือส่งตัวนักศึกษา', category: FormCategory.APPLICATION, url: '#' },
  { id: 'f3', title: 'บันทึกการปฏิบัติงานรายสัปดาห์', category: FormCategory.MONITORING, url: '#' },
  { id: 'f4', title: 'แบบประเมินผลโดยสถานประกอบการ', category: FormCategory.MONITORING, url: '#' },
];
