
import { Language, Major, InternshipSite, DocumentForm, FormCategory, ScheduleEvent, Translation, ApplicationStatus, StudentStatusRecord } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.TH]: {
    title: "หน่วยจัดการศึกษาวิทยาศาสตร์บูรณาการกับการทำงาน (วบง.)",
    subtitle: "คณะวิทยาศาสตร์และเทคโนโลยี มหาวิทยาลัยฟาฏอนี",
    landingHeading: "การฝึกประสบการณ์และสหกิจศึกษา",
    loginStudent: "ทางเข้าสำหรับนักศึกษา",
    loginAdmin: "ระบบจัดการสำหรับผู้ดูแล",
    studentIdPlaceholder: "รหัสประจำตัวนักศึกษา",
    adminPasswordPlaceholder: "รหัสผ่านเจ้าหน้าที่",
    loginButton: "ยืนยันการเข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    internshipSites: "ฐานข้อมูลสถานประกอบการ",
    forms: "ศูนย์บริการเอกสารอิเล็กทรอนิกส์",
    halalMajor: "สาขาวิชาวิจัยและพัฒนาผลิตภัณฑ์อาหารฮาลาล",
    digitalMajor: "สาขาวิชาเทคโนโลยีและวิทยาการดิจิทัล",
    allMajors: "ทุกสาขาวิชา",
    activeSites: "เปิดรับสมัคร",
    pastSites: "ประวัติการฝึก",
    seniorVisitedSites: "รุ่นพี่เคยมาแล้ว",
    download: "ดาวน์โหลด",
    adminPanel: "แผงควบคุม",
    addSite: "เพิ่มหน่วยงาน",
    edit: "แก้ไข",
    delete: "ลบ",
    save: "บันทึก",
    cancel: "ยกเลิก",
    name: "ชื่อหน่วยงาน",
    location: "สถานที่",
    description: "รายละเอียด",
    status: "สถานะ",
    major: "สาขาวิชา",
    urlLabel: "ลิงก์เว็บไซต์",
    selectMajorTitle: "เลือกสาขาวิชาของคุณ",
    selectMajorSubtitle: "เพื่อดูข้อมูลที่ตรงกับความต้องการ",
    startNow: "เข้าสู่เว็บไซต์",
    checkStatus: "ติดตามสถานะ",
    selectLanguagePrompt: "กรุณาเลือกภาษา",
    schedule: "กำหนดการสำคัญ",
    appForms: "เอกสารสมัครงาน",
    monitoringForms: "เอกสารระหว่างฝึกงาน",
    email: "อีเมล",
    phone: "โทรศัพท์",
    visitWebsite: "ไปที่เว็บไซต์",
    searchPlaceholder: "ค้นหาชื่อหน่วยงาน ตำแหน่ง หรือจังหวัด...",
    statusPending: "กำลังตรวจสอบเอกสาร",
    statusPreparing: "กำลังจัดเตรียมเอกสาร",
    statusAccepted: "ถูกตอบรับจากสถานประกอบการ",
    statusRejected: "ถูกปฏิเสธจากสถานประกอบการ",
    statusTitle: "ตรวจสอบสถานะการสมัคร",
    statusCheckPrompt: "กรุณาระบุรหัสนักศึกษาเพื่อตรวจสอบ",
    noStatusFound: "ไม่พบข้อมูลสถานะสำหรับรหัสนักศึกษานี้",
    lastUpdated: "อัปเดตล่าสุด",
    searchButton: "ค้นหาข้อมูล",
    studentLabel: "นักศึกษา",
    currentStatusLabel: "สถานะปัจจุบัน",
    adminStudentSearchPlaceholder: "ค้นหาชื่อหรือรหัสนักศึกษา...",
    startDateLabel: "เริ่ม:",
    endDateLabel: "สิ้นสุด:",
    docHubTitle: "ดาวน์โหลดแบบฟอร์มและเอกสารสำคัญ",
    docHubButton: "เปิดศูนย์บริการเอกสาร",
    docHubContact: "หากพบปัญหาในการดาวน์โหลด กรุณาติดต่อเจ้าหน้าที่ วบง."
  },
  [Language.EN]: {
    title: "Work-Integrated Science Education Unit (WISE)",
    subtitle: "Faculty of Science and Technology, Fatoni University",
    landingHeading: "Internship & Co-operative Education",
    loginStudent: "Student Portal",
    loginAdmin: "Admin Management",
    studentIdPlaceholder: "Student ID",
    adminPasswordPlaceholder: "Staff Password",
    loginButton: "Login",
    logout: "Logout",
    internshipSites: "Internship Database",
    forms: "Electronic Document Center",
    halalMajor: "Halal Food Research and Development",
    digitalMajor: "Digital Technology and Science",
    allMajors: "All Majors",
    activeSites: "Now Hiring",
    pastSites: "History",
    seniorVisitedSites: "Previously Visited",
    download: "Download",
    adminPanel: "Admin Panel",
    addSite: "Add Site",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    name: "Organization Name",
    location: "Location",
    description: "Description",
    status: "Status",
    major: "Major",
    urlLabel: "Website URL",
    selectMajorTitle: "Select Your Major",
    selectMajorSubtitle: "To view relevant information",
    startNow: "Enter Website",
    checkStatus: "Track Status",
    selectLanguagePrompt: "Select Language",
    schedule: "Key Schedule",
    appForms: "Application Forms",
    monitoringForms: "Monitoring Forms",
    email: "Email",
    phone: "Phone",
    visitWebsite: "Visit Website",
    searchPlaceholder: "Search site, position, or city...",
    statusPending: "Documents Under Review",
    statusPreparing: "Processing Documents",
    statusAccepted: "Accepted by Company",
    statusRejected: "Application Not Selected",
    statusTitle: "Check Application Status",
    statusCheckPrompt: "Enter Student ID to check",
    noStatusFound: "No status found for this Student ID",
    lastUpdated: "Last Updated",
    searchButton: "Search Information",
    studentLabel: "Student",
    currentStatusLabel: "Current Status",
    adminStudentSearchPlaceholder: "Search name or student ID...",
    startDateLabel: "Start:",
    endDateLabel: "End:",
    docHubTitle: "Download Forms & Important Documents",
    docHubButton: "Open Document Hub",
    docHubContact: "If you have trouble downloading, please contact WISE staff."
  },
  [Language.AR]: {
    title: "وحدة تعليم العلوم المتكاملة مع العمل (WISE)",
    subtitle: "كلية العلوم والتكنولوجيا ، جامعة فطاني",
    landingHeading: "التدريب الميداني والتعليم التعاوني",
    loginStudent: "بوابة الطالب",
    loginAdmin: "إدارة النظام",
    studentIdPlaceholder: "الرقم الجامعي",
    adminPasswordPlaceholder: "كلمة مرور الموظف",
    loginButton: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    internshipSites: "قاعدة بيانات التدريب",
    forms: "مركز الوثائق الإلكترونية",
    halalMajor: "تخصص بحوث وتطوير الأغذية الحلال",
    digitalMajor: "تخصص علوم وتكنولوجيا التكنولوجيا الرقمية",
    allMajors: "جميع التخصصات",
    activeSites: "มتاح الآن",
    pastSites: "السجل السابق",
    seniorVisitedSites: "زار من قبل",
    download: "تحميل",
    adminPanel: "لوحة التحكم",
    addSite: "إضافة موقع",
    edit: "تعديل",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    name: "اسم المنظمة",
    location: "الموقع",
    description: "الوصف",
    status: "الحالة",
    major: "التخصص",
    urlLabel: "رابط الموقع",
    selectMajorTitle: "اختر تخصصك",
    selectMajorSubtitle: "لعرض المعلومات ذات الصلة",
    startNow: "الدخول إلى الموقع",
    checkStatus: "متابعة الحالة",
    selectLanguagePrompt: "اختر اللغة",
    schedule: "الجدول الزمني",
    appForms: "نماذج التقديم",
    monitoringForms: "نماذج المتابعة",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    visitWebsite: "زيارة الموقع",
    searchPlaceholder: "البحث عن اسم أو مكان...",
    statusPending: "جاري فحص المستندات",
    statusPreparing: "جاري تحضير المستندات",
    statusAccepted: "تم القبول من المنظمة",
    statusRejected: "تم الرفض من المنظمة",
    statusTitle: "التحقق من حالة التقديم",
    statusCheckPrompt: "أدخل الرقم الجامعي للتحقق",
    noStatusFound: "لم يتم العثور على حالة لهذا الرقم الجامعي",
    lastUpdated: "آخر تحديث",
    searchButton: "بحث",
    studentLabel: "طالب",
    currentStatusLabel: "الحالة الحالية",
    adminStudentSearchPlaceholder: "البحث عن الاسم หรือ الرقم الجامعي...",
    startDateLabel: "يبدأ:",
    endDateLabel: "ينتهي:",
    docHubTitle: "تحميل النماذج والوثائق الهامة",
    docHubButton: "افتح مركز الوثائق",
    docHubContact: "إذا واجهت مشاكل في التحميل ، يرجى الاتصال بموظفي WISE."
  },
  [Language.MS]: {
    title: "Unit Pendidikan Sains Bersepadu Kerja (WISE)",
    subtitle: "Fakulti Sains dan Teknologi, Universiti Fatoni",
    landingHeading: "Latihan Industri & Pendidikan Ko-operatif",
    loginStudent: "Portal Pelajar",
    loginAdmin: "Pengurusan Admin",
    studentIdPlaceholder: "ID Pelajar",
    adminPasswordPlaceholder: "Kata Laluan Staf",
    loginButton: "Log Masuk",
    logout: "Log Keluar",
    internshipSites: "Pangkalan Data Latihan",
    forms: "Pusat Dokumen Elektronik",
    halalMajor: "Penyelidikan Produk Halal",
    digitalMajor: "Teknologi Digital",
    allMajors: "Semua Bidang",
    activeSites: "Sedang Dibuka",
    pastSites: "Rekod Lepas",
    seniorVisitedSites: "Pernah Dilawati",
    download: "Muat Turun",
    adminPanel: "Panel Admin",
    addSite: "Tambah Tapak",
    edit: "Edit",
    delete: "Padam",
    save: "Simpan",
    cancel: "Batal",
    name: "Nama Organisasi",
    location: "Lokasi",
    description: "Keterangan",
    status: "Status",
    major: "Bidang",
    urlLabel: "Pautan Laman Web",
    selectMajorTitle: "Pilih Bidang Anda",
    selectMajorSubtitle: "Untuk melihat maklumat yang berkaitan",
    startNow: "Masuk ke Laman Web",
    checkStatus: "Semak Status",
    selectLanguagePrompt: "Sila Pilih Bahasa",
    schedule: "Jadual Penting",
    appForms: "Borang Permohonan",
    monitoringForms: "Borang Pemantauan",
    email: "Emel",
    phone: "Telefon",
    visitWebsite: "Layari Laman Web",
    searchPlaceholder: "Cari nama, jawatan, atau tempat...",
    statusPending: "Dokumen sedang disemak",
    statusPreparing: "Dokumen sedang disediakan",
    statusAccepted: "Diterima oleh organisasi",
    statusRejected: "Ditolak oleh organisasi",
    statusTitle: "Semak Status Permohonan",
    statusCheckPrompt: "Sila masukkan ID Pelajar",
    noStatusFound: "Tiada status dijumpai untuk ID Pelajar ini",
    lastUpdated: "Kemas Kini Terakhir",
    searchButton: "Cari Maklumat",
    studentLabel: "Pelajar",
    currentStatusLabel: "Status Semasa",
    adminStudentSearchPlaceholder: "Cari nama หรือ ID Pelajar...",
    startDateLabel: "Mula:",
    endDateLabel: "Tamat:",
    docHubTitle: "Muat Turun Borang & Dokumen Penting",
    docHubButton: "Buka Pusat Dokumen",
    docHubContact: "Jika anda menghadapi masalah memuat turun, sila hubungi kakitangan WISE."
  }
};

export const INITIAL_SITES: InternshipSite[] = [
  {
    id: "1",
    name: { th: "บริษัท ฮาลาลแลนด์ จำกัด", en: "Halal Land Co., Ltd.", ar: "شركة أرض الحلال المحدودة", ms: "Halal Land Sdn Bhd" },
    location: { th: "กรุงเทพมหานคร", en: "Bangkok", ar: "بانكوك", ms: "Bangkok" },
    description: { th: "วิจัยและพัฒนาผลิตภัณฑ์อาหารฮาลาลมาตรฐานสากล", en: "Research and development of international standard halal food products.", ar: "البحث والتطوير لمنتجات الأغذية الحلال ذات المعايير الدولية.", ms: "Penyelidikanและ pembangunan produk makanan halal bertaraf antarabangsa." },
    position: { th: "เจ้าหน้าที่ควบคุมคุณภาพ (QC)", en: "Quality Control Officer (QC)", ar: "مسؤول مراกبة الجودة", ms: "Pegawai Kawalan Kualiti" },
    status: 'active',
    major: Major.HALAL_FOOD,
    email: "hr@halalland.com",
    contactLink: "https://halalland.com"
  },
  {
    id: "2",
    name: { th: "เทคโพร โซลูชั่น", en: "TechPro Solutions", ar: "حلول تيك برو", ms: "TechPro Solutions" },
    location: { th: "ภูเก็ต", en: "Phuket", ar: "بوكيت", ms: "Phuket" },
    description: { th: "บริษัทพัฒนาซอฟต์แวร์และระบบคลาวด์", en: "Software development and cloud solutions company.", ar: "شركةพัฒนาซอฟต์แวร์และระบบคลาวด์.", ms: "Syarikat pembangunan perisianและ penyelesaian awan." },
    position: { th: "Full Stack Developer", en: "Full Stack Developer", ar: "مطور فول ستاك", ms: "Pembangun Full Stack" },
    status: 'active',
    major: Major.DIGITAL_TECH,
    email: "careers@techpro.io",
    contactLink: "https://techpro.io"
  }
];

export const INITIAL_FORMS: DocumentForm[] = [
  { 
    id: "f1", 
    title: { 
      th: "แบบฟอร์มขอฝึกงาน (วบง. 01)", 
      en: "Internship Request Form (WISE 01)", 
      ar: "نموذج طلب التدريب (วบง. 01)", 
      ms: "Borang Permohonan Latihan (WISE 01)" 
    }, 
    category: FormCategory.APPLICATION, 
    url: "#" 
  },
  { 
    id: "f2", 
    title: { 
      th: "ใบสมัครสหกิจศึกษา (วบง. 02)", 
      en: "Co-operative Education Application (WISE 02)", 
      ar: "طلب التعليم التعاوني (วบง. 02)", 
      ms: "Permohonan Pendidikan Ko-operatif (WISE 02)" 
    }, 
    category: FormCategory.APPLICATION, 
    url: "#" 
  },
  { 
    id: "f3", 
    title: { 
      th: "แบบบันทึกการปฏิบัติงานรายสัปดาห์", 
      en: "Weekly Performance Record", 
      ar: "سجل الأداء الأسبوعي", 
      ms: "Rekod Prestasi Mingguan" 
    }, 
    category: FormCategory.MONITORING, 
    url: "#" 
  },
  { 
    id: "f4", 
    title: { 
      th: "แบบประเมินผลการฝึกงาน (สำหรับพี่เลี้ยง)", 
      en: "Internship Evaluation Form (For Supervisors)", 
      ar: "نموذج تقييم التدريب (للمشرفين)", 
      ms: "Borang Penilaian Latihan (Untuk Penyelia)" 
    }, 
    category: FormCategory.MONITORING, 
    url: "#" 
  }
];

export const INITIAL_SCHEDULE: ScheduleEvent[] = [
  {
    id: "s1",
    event: { th: "เปิดรับสมัครการฝึกงาน/สหกิจศึกษา", en: "Internship Application Period", ar: "فترة التقديم للتدريب", ms: "Tempoh Permohonan Latihan Industri" },
    startDate: { th: "1 มกราคม 2568", en: "Jan 1, 2025", ar: "١ يناير ٢٠٢٥", ms: "1 Jan 2025" },
    endDate: { th: "31 มกราคม 2568", en: "Jan 31, 2025", ar: "٣١ يناير ٢٠٢٥", ms: "31 Jan 2025" },
    status: 'upcoming'
  }
];

export const INITIAL_STUDENT_STATUSES: StudentStatusRecord[] = [
  { id: "st1", studentId: "406123456", name: "สมชาย รักเรียน", status: ApplicationStatus.PENDING, major: Major.HALAL_FOOD, lastUpdated: Date.now() },
  { id: "st2", studentId: "406123457", name: "สมหญิง ขยันหมั่นเพียร", status: ApplicationStatus.ACCEPTED, major: Major.DIGITAL_TECH, lastUpdated: Date.now() },
  { id: "st3", studentId: "406123458", name: "อับดุลลอฮ์ มานะ", status: ApplicationStatus.PREPARING, major: Major.HALAL_FOOD, lastUpdated: Date.now() },
  { id: "st4", studentId: "406123459", name: "มารีอัม สาและ", status: ApplicationStatus.REJECTED, major: Major.DIGITAL_TECH, lastUpdated: Date.now() }
];
